name: node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Run install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy the application
        run: npm run deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      - name: Archive npm fail logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Run install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results
