name: Data Passing Workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Data
      run: echo "Some data generated in Job 1" > data.txt
    - name: Upload data as artifact
      uses: actions/upload-artifact@v2
      with:
        name: data-artifacts
        path: data.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Download data artifacts
      uses: actions/download-articats@v2
      with:
        name: data-artifacts
        path: data/
    - name: Use data in job2
      run: cat data/data.txt
